SET(EXTH-SUITE_HEADERS)
    
SET(EXTH-SUITE_SOURCES)

SET(EXTH-SUITE_FORMS)

QT5_WRAP_UI(EXTH-SUITE_FORM_INCLUDES ${EXTH-SUITE_FORMS})


SET(EXTH-SUITE_CONFIG_FILES
    ${EXTH-SUITE_SRC_DIR}/CMakeLists.txt
    ${EXTH-SUITE_SRC_DIR}/FileLists.cmake
    ${EXTH-SUITE_SRC_DIR}/LibLists.cmake)

SET(EXTH-SUITE_SRC_FILES
    ${EXTH-SUITE_HEADERS}
    ${EXTH-SUITE_SOURCES}
    ${EXTH-SUITE_FORMS}
    ${EXTH-SUITE_FORM_INCLUDES}
    ${EXTH-SUITE_CONFIG_FILES}
    ${EXANIMATOR_SRC_FILES}
    ${EXCOMPOSITOR_SRC_FILES})


# Visual Studio filters
SOURCE_GROUP("Header Files" FILES ${EXTH-SUITE_HEADERS})
SOURCE_GROUP("Source Files" FILES ${EXTH-SUITE_SOURCES})
SOURCE_GROUP("Form Files" FILES ${EXTH-SUITE_FORMS})
SOURCE_GROUP("Config" FILES ${EXTH-SUITE_CONFIG_FILES})
