# Qt
FIND_PACKAGE(Qt5OpenGL REQUIRED)
FIND_PACKAGE(Qt5Multimedia REQUIRED)
SET(CMAKE_AUTOMOC ON)
SET(CMAKE_INCLUDE_CURRENT_DIR ON)

# ExTh
SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH}
    "${EXTH-SUITE_SRC_DIR}/../ExperimentalTheatre/")
FIND_PACKAGE(ExperimentalTheatre REQUIRED)

#Globals
SET(EXTH-SUITE_LIBRARIES
    ${ExTh_LIBRARIES})
SET(EXTH-SUITE_INCLUDE_DIRS
    ${EXTH-SUITE_INCLUDE_DIRS}
    ${EXTH-SUITE_SRC_DIR}
    ${ExTh_INCLUDE_DIRS})
SET(EXTH-SUITE_QT_MODULES
    OpenGL
    Multimedia)

